-- ~/.config/nvim/lua/plugins/which-key.lua
-- which-key configuration from reference repo

local ok, wk = pcall(require, 'which-key')
if not ok then return end

wk.setup({
  delay = 120,
  notify = false,
  win = { border = 'single' },
})

wk.add({
  { '<Space> b', group = 'buffers' },
  { '<Space> s', group = 'split/screen' },
  { '<Space> sv', desc = 'Split vertical' },
  { '<Space> sh', desc = 'Split horizontal' },
  { '<Space> sc', desc = 'Split close' },
  { '<Space> so', desc = 'Split only' },
  { '<Space> se', desc = 'Split equalize' },
  { '<Space> sr', desc = 'Split resize mode (arrows, Esc quit)' },
  { '<Space> sH', desc = 'Split resize left (count x 6)' },
  { '<Space> sJ', desc = 'Split resize down (count x 6)' },
  { '<Space> sK', desc = 'Split resize up (count x 6)' },
  { '<Space> sL', desc = 'Split resize right (count x 6)' },
  { '<Space> f', group = 'find/files' },
  { '<Space> ff', desc = 'Find files' },
  { '<Space> fg', desc = 'Find grep' },
  { '<Space> fw', desc = 'Find word under cursor' },
  { '<Space> fr', desc = 'Find resume' },
  { '<Space> fh', desc = 'Find home' },
  { '<Space> fc', desc = 'Find config' },
  { '<Space> fl', desc = 'Find local src' },
  { '<Space> a', group = 'actions/file' },
  { '<Space> as', desc = 'Action save' },
  { '<Space> aa', desc = 'Action save as' },
  { '<Space> am', desc = 'Action move file' },
  { '<Space> ax', desc = 'Action chmod +x' },
  { '<Space> t', group = 'test/term' },
  { '<Space> tt', desc = 'Terminal toggle' },
  { '<Space> tn', desc = 'Test nearest' },
  { '<Space> tf', desc = 'Test file' },
  { '<Space> ts', desc = 'Test suite' },
  { '<Space> tl', desc = 'Test last' },
  { '<Space> tv', desc = 'Test visit' },
  { '<Space> u', group = 'ui' },
  { '<Space> ut', desc = 'UI toggle theme' },
  { '<Space> uw', desc = 'UI toggle wrap' },
  { '<Space> un', desc = 'UI toggle relative numbers' },
  { '<Space> o', group = 'open' },
  { '<Space> ou', desc = 'Open URL' },
  { '<Space> of', desc = 'Open file folder' },
  { '<Space> g', group = 'git' },
  { '<Space> gs', desc = 'Git status' },
  { '<Space> gd', desc = 'Git diff split' },
  { '<Space> gD', desc = 'Git diffview open' },
  { '<Space> gb', desc = 'Git blame' },
  { '<Space> gh', desc = 'Git file history' },
  { '<Space> gq', desc = 'Git diffview close' },
  { '<Space> k', group = 'help/keymaps' },
  { '<Space> km', desc = 'Help open nvim keymaps' },
  { '<Space> kt', desc = 'Help open tmux keymaps' },
  { '<Space> p', group = 'plugins' },
  { '<Space> pi', desc = 'Plugins install' },
  { '<Space> r', group = 'replace/reload' },
  { '<Space> rr', desc = 'Replace all' },
  { '<Space> rc', desc = 'Reload current file' },
  { '<Space> x', group = 'trouble/lists' },
  { '<Space> xx', desc = 'Trouble toggle diagnostics' },
  { '<Space> xd', desc = 'Trouble buffer diagnostics' },
  { '<Space> xq', desc = 'Trouble quickfix list' },
  { '<Space> xl', desc = 'Trouble location list' },
  { '<Space> z', group = 'folds' },
  { '<Space> zc', desc = 'Fold close' },
  { '<Space> zo', desc = 'Fold open' },
  { '<Space> za', desc = 'Fold toggle' },
  { '<Space> zM', desc = 'Fold close all' },
  { '<Space> zR', desc = 'Fold open all' },
  { '<Space> m', group = 'make' },
  { '<Space> c', group = 'code' },
})
